package exampledata

/***
  * http://www.hadbara.moag.gov.il/hadbara/english/search/disinfEng_Crops_new.asp
  */
object Crops {
  val set = Set(
    "ABUTILON",
    "BEANS DRY",
    "ACHILLEA",
    "ACHSINENTUS",
    "ACONITUM",
    "ADENIUM",
    "AGERATUM",
    "ALFALFA",
    "ALMOND",
    "ANARYLLIS",
    "ANEMONE",
    "ANETHUM",
    "ANIGOZANTHUS",
    "ANIMAL FEED STUFFS",
    "ANONA",
    "ANTIRRHINUM",
    "APPLE",
    "APPLE POMACE",
    "APRICOT",
    "ARALIA",
    "ARAUCARIA",
    "ARDIZIA",
    "ARIGATHUS",
    "ARTICHOKE",
    "ASCLEPIAS",
    "ASPARAGUS",
    "ASPELINIUM",
    "ASPIDISTRA",
    "ASTER",
    "AVOCADO",
    "BANANA",
    "BARBATUS",
    "BARLEY",
    "BARLEY STRAW",
    "BASIL",
    "BEAN VINE",
    "BEANS",
    "BEET, GREENS",
    "BEETROOT",
    "BEGONIA",
    "BELL PEPPER",
    "BIOLOGICAL CROPS",
    "BLACKBERRY",
    "BOCK CHOY LEAVES",
    "BOHYNIA",
    "BONGAINVILLEA",
    "BRAN",
    "BRASSICA",
    "BROAD BEAN",
    "BROCCOLI",
    "BRUSSELS SPROUTS",
    "BUCKWEAT",
    "BULB VEGETABLE",
    "BULBS",
    "CABBAGE",
    "CABBAGE SAVOY",
    "CACAO BEANS",
    "CALENDULA",
    "CALLA",
    "CALLISTEMON",
    "CALMONADIN",
    "CANARY PALM",
    "CANTALOUP",
    "CARCASE MEAT",
    "CARNATION",
    "CAROB",
    "CARROT",
    "CASHEW",
    "CASUARINA",
    "CATTLE",
    "CAULIFLOWER",
    "CELERIAC",
    "CELERY",
    "CEREALS",
    "CHAMDURIEA",
    "CHARD",
    "CHEESE",
    "CHERBIL",
    "CHERRY",
    "CHESTNUTS",
    "CHESTRUM",
    "CHICK PEA",
    "CHICORY",
    "CHILI PEPPER",
    "CHINESE CABBAGE",
    "Chinese sprouts",
    "CHIVES",
    "CHIX",
    "CHRYSANTHEMUM",
    "CINERARIA",
    "CITRON",
    "CITRUS FRUIT",
    "CITRUS JUICE",
    "CLEMENTINE",
    "CLOVER",
    "COCOA BUTTER",
    "COCOA MASS",
    "COFFEE BEANS",
    "COLD STORAGE ROOMS",
    "COLRUTARIA",
    "Compost",
    "CORCHORUS OLITORIUS",
    "CORDLYN",
    "CORIANDER",
    "CORN",
    "COTONEASTER",
    "COTTON",
    "COTTON FORAGE",
    "COTTONSEED OIL",
    "COWPEA",
    "CROTON",
    "CUCUMBER",
    "CUCURBITS",
    "CUPRESSUS",
    "CURRANT",
    "CYMBOPOGON",
    "DAHLIA",
    "DASTERIUM",
    "DATE",
    "DECIDUOUS FRUIT TREES",
    "DELBARGIA",
    "DELICHIOZA",
    "DELPHINIUM CONSOLIDA",
    "DETACHED ROOT BED",
    "DEWBERRIES",
    "DIFFENBACHIA",
    "DILL",
    "DRAGONFRUIT",
    "DRAINAGE TRENCH",
    "DRIED FISH",
    "DRIED FOOD",
    "DRIED FRUIT",
    "DRIED VEGETABLES",
    "DURANTA",
    "EASTER LILY",
    "EASY PEALER",
    "ECHINOPS SP.",
    "EDIBLE OFFAL",
    "EDIBLE VEGETABLE OIL",
    "EGG PLANT",
    "EGGS",
    "ENDIVES",
    "ESTRAGON",
    "EUCALYPTUS",
    "EUONYMUS",
    "EUPHORBIA",
    "EUROPEAN PLUM",
    "EVONIMUS",
    "FALLOE",
    "FAT",
    "FEIJOA",
    "FENNEL",
    "FERNS",
    "FICUS",
    "FICUS PUMILA",
    "FIELD CROPS",
    "FIELD PREPARATION",
    "FIG",
    "FILBERT",
    "FISH",
    "FISH PONDS",
    "FISTACHIA",
    "FLAX",
    "FLOUR",
    "FLOWERS",
    "FODDER",
    "FODDER BEET",
    "FORAGE CORN",
    "FORAGE CROPS",
    "FOREST",
    "FRENCH BEAN",
    "FRUITING VEGETABLE",
    "FRUITS",
    "FUCHSIA",
    "GARDINIA",
    "GARLIC",
    "GENTAUREA",
    "GERANIUM",
    "GERBERA",
    "GHERKIN",
    "GINGER",
    "GLADIOLI",
    "GLOBOLARIA",
    "GLOXINIA",
    "GOAT",
    "GODETIA",
    "GODTIA",
    "GOOSEBERRY",
    "GRAIN CORN",
    "GRAINS",
    "GRAINS, STORAGE",
    "GRAPE POMACE",
    "GRAPEFRUIT",
    "GRAPES",
    "GRASS",
    "GRAZING LAND",
    "GREVILLEA",
    "GUAVA",
    "GYPSOPHILA",
    "HAY",
    "HAZELNUTS",
    "HEDERA",
    "HELIANTHUS",
    "HERBS",
    "HIBISCUS",
    "HILBA",
    "HIPPEASTRUM",
    "HOGS",
    "HOPS",
    "HORSERADISH",
    "HORSES",
    "HYDRANGEA",
    "HYPERICUM",
    "HYPOESTES",
    "HYPOESTES PHYLLOSTACHY",
    "HYSSOP",
    "IMPETIANS",
    "INDUSTRIAL CROPS",
    "IRIS",
    "IXIA",
    "IXORA",
    "JACARANDA",
    "JANIPERUS",
    "JAPANESE PLUM",
    "JAPANESE RADISH",
    "JASMIN",
    "JUJUBE CHINESE(SIMMONDSIA",
    "KALANCHOE'",
    "KALE",
    "KIWI",
    "KOCHIA",
    "KOHLRABI",
    "KOLEOS",
    "KUMQUATS",
    "LANTENA",
    "LAWN",
    "LEAFY VEGETABLES",
    "LEEK",
    "LEGUME OILSEEDS",
    "LEGUME SEEDS",
    "LEGUME VEGETABLE",
    "LEGUMS",
    "LEMONS",
    "LENTILS",
    "LEPTOSPERMON",
    "LEPTOSPERMUM",
    "LETTUCE",
    "LIATRIS",
    "LICHEE",
    "LILIUM",
    "LIMES",
    "LIMONIUM BELTLAARD",
    "LIMONIUM SENUATUM",
    "LIMQUAT",
    "LINSEED",
    "LINSEED OIL",
    "LISIANTUS",
    "LOQUAT",
    "LOVAGE",
    "LUISA",
    "LYATHYRUS OBORATUS",
    "LYGUSTRUM",
    "LYSIMACHIA",
    "MACADAMIA NUTS",
    "MACROPHYLLA",
    "MAIZ OIL",
    "MAMMALIAN",
    "MANDARIN",
    "MANDEVILLA",
    "MANGO",
    "MARJORAM",
    "MASANJANA",
    "MATRICARIA",
    "MATTHIOLA",
    "MEAT",
    "MELALEUCA",
    "MELISA",
    "MELON",
    "MILK",
    "MILK PRODUCTS",
    "MILLET",
    "MINEOLA",
    "MINT",
    "MIROCLAUDIUS",
    "MISCELLANEOUS FOOD",
    "MIZONA",
    "MONSTERA")

}


